### ISSUE TITLE
Những phản hồi về công cụ DSL4Wearable

### ISSUE THREAD

**Issue by esp-lab** [esp-lab/DSL4Wearable#1]
Những phản hồi về công cụ DSL4W, xin vui lòng gửi thông tin lại đây. Nhóm tác giả sẽ xem xét và phản hồi sớm nhất. Xin chân thành cám ơn!

**Comment by HuuThuat1996** [comment]
bạn chụp hình dùm mình nhé

**Comment by esp-lab** [comment]
Chào @lochoang75 , cho hỏi bạn dùng hệ điều hành nào vậy?

**Comment by lochoang75** [comment]
Mình dùng linux mint 18. lỗi đó mình thấy trong file log, code vẫn generate ra bình thường nhưng xuất hiện một số lỗi.

**Comment by lochoang75** [comment]
bạn mình dùng với cùng stateschema thì generate successful mà không có lỗi gì.

**Comment by HuuThuat1996** [comment]
do cái tool này mình phát triển trên window nên một số lỗi phát sinh trên linux mình chưa kiểm soát được. Trong các bản cập nhật tới sẽ chú ý đến phần này

**Comment by esp-lab** [comment]
Nếu các file phát sinh ra có file manual.html thì vẫn ổn. Lỗi này có ý nghĩa liên quan đến file manual.html, nên sẽ không ảnh hưởng đến code .ino khi phát sinh

**Comment by lochoang75** [comment]
Mình cũng nghĩ thế. Cảm ơn! Chúc nhóm thành công

**Comment by akkiensama** [comment]
Cho mình hỏi cách sử dụng Decision trong state schema. Cảm ơn

**Comment by esp-lab** [comment]
Trong lược đồ state machine sẽ không có decision bạn nhé, hiện công cụ chỉ hiển thị lên nhưng sẽ remove phiên bản sau. Cám ơn phản hồi của bạn akkiensama

**Comment by akkiensama** [comment]
![bug](https://user-images.githubusercontent.com/25955537/47600937-f75a3f80-d9f2-11e8-943b-ac94b3e2848d.PNG)
mình làm theo chính xác hướng dẫn của trong lab3 của tutorial nhưng khi sinh code thì trạng thái start lại không hiển thị gì hết. Mình có sửa state scheme hiển những chữ khác nhưng vẫn bị như vậy. Cảm ơn!

**Comment by HuuThuat1996** [comment]
trường hợp của bạn mình sẽ kiểm tra lại vấn đề và thông báo sớm nhất

**Comment by lochoang75** [comment]
mình bị lỗi kéo dây, các dây nối rất loạn và không theo ý muốn của người kéo.
![image](https://user-images.githubusercontent.com/30142021/47617159-07f3de00-daf7-11e8-8bb5-1d99d64bd6f9.png)

**Comment by WatashiMo** [comment]
### Ví dụ sử dụng 3 đèn led để bật tắt đèn giao thông xuất dữ liệu ra màn hình LCD ### 
![capture](https://user-images.githubusercontent.com/41546531/47626316-0f4dd280-db5d-11e8-8768-212f5048a899.PNG)
### Hướng dẫn cắm mạch ### 
![capture2](https://user-images.githubusercontent.com/41546531/47626600-8fc10300-db5e-11e8-9947-a67660bca3da.PNG)

#include <LiquidCrystal_I2C.h>

int currentState = 0;
int nextState = -1;
const int red = 2;
const int green = 3;
const int yellow = 4;
LiquidCrystal_I2C lcd(0x27, 20, 4);


void stateStart();
void stateState1();
void stateState2();
void setup()
{
  pinMode(red, OUTPUT);
  pinMode(green, OUTPUT);
  pinMode(yellow, OUTPUT);
  lcd.init();
  lcd.begin(20, 4);
  lcd.backlight();
  if(currentState == 0){
    stateStart();
  }
}
void loop()
{
  switch(currentState){
    case 0:
    stateState1();
    break;
    case 1:
    stateState2();
    break;
    case 2:
    stateStart();
    break;
    default:
    break;
  }
}

void stateStart(){
  digitalWrite(red, LOW);
  digitalWrite(green, HIGH);
  digitalWrite(yellow, LOW);
  lcd.clear();
  lcd.setCursor(0,1);
  lcd.print("Xin Chao");
  delay(3000);
  currentState = 0;
}
void stateState1(){
  digitalWrite(red, LOW);
  digitalWrite(green, LOW);
  digitalWrite(yellow, HIGH);
  lcd.clear();
  lcd.setCursor(0,1);
  lcd.print("Cham");
delay(3000);
  currentState = 1;
}
void stateState2(){
  digitalWrite(red, HIGH);
  digitalWrite(green, LOW);
  digitalWrite(yellow, LOW);
  lcd.clear();
  lcd.setCursor(0,0); 
  lcd.print("Dung"); 
  delay(3000);
  currentState = 2;
}
_Chương trình khu phát sinh code ra thì thiếu lện xuất ra màn hình của LCD cái này mình cũng không biết sao nữa, trên kia là code hoàn chỉnh của nó, các bạn tham khảo nhe_

**Comment by esp-lab** [comment]
> mình bị lỗi kéo dây, các dây nối rất loạn và không theo ý muốn của người kéo.
> ![image](https://user-images.githubusercontent.com/30142021/47617159-07f3de00-daf7-11e8-8bb5-1d99d64bd6f9.png)

Chào bạn!

Hiện công cụ cho phép người dùng kéo thả và di chuyển các đối tượng theo ý muốn. Các mũi tên mình di chuyển thì phải chọn điểm chính giữa của mũi tên để di chuyển. Nhìn chung vẫn còn khó khăn khi di chuyển vì công cụ xử dụng thư viện GMF, GEF nên cũng chưa hoàn thiện hết!

**Comment by akkiensama** [comment]
Mình phát hiện bug về button. Nếu dùng nhiều button trong , dù state schema có sử dụng button gì đi chăng nữa thì code sinh ra luôn là button cuối cùng trong danh sách thiết bị.

**Comment by HungSoma** [comment]
Cũng bị lỗi button như bạn ở trên

**Comment by HuuThuat1996** [comment]
cám ơn các bạn đã phản hồi về lỗi này. Chúng mình sẽ khắc phục trong thời
gian sớm nhất

Vào Th 2, 29 thg 10, 2018 vào lúc 22:51 HungSoma <notifications@github.com>
đã viết:

**Comment by leminh0796** [comment]
![capture](https://user-images.githubusercontent.com/26307324/47708854-93897e00-dc61-11e8-9a6b-3db584e7f7e5.JPG)
Lỗi sau khi nhấn nút chương trình chuyển trạng thái 1 (cần điều kiện nút nhấn) nhưng nếu tồn tại thêm trạng thái 2 (không điều kiện) thì chương trình sẽ nhảy qua trạng thái thứ 2.

**Comment by esp-lab** [comment]
Thanks for minhphucanhnguyen's feedback. We'll check again for these issues. Thanks again

**Comment by esp-lab** [comment]
@ngocmy177  Bạn có thể gửi cho team 2 file: device và state cho vấn đề ở đây https://github.com/esp-lab/DSL4Wearable/issues/5 không. Cảm ơn.

**Comment by esp-lab** [comment]
> mình bị lỗi kéo dây, các dây nối rất loạn và không theo ý muốn của người kéo.
> ![image](https://user-images.githubusercontent.com/30142021/47617159-07f3de00-daf7-11e8-8bb5-1d99d64bd6f9.png)

Vấn đề này đã được fixed. Bạn thử download phiên bản từ beta.0.2.1 trở lên. 
Link download tại đây https://github.com/esp-lab/DSL4Wearable/releases
