### ISSUE TITLE
Đóng góp nhỏ để DSL4Wearable ngày càng hoàn thiện

### ISSUE THREAD

**Issue by nhimrmh** [esp-lab/DSL4Wearable#14]
Chào team phát triển DSL4Wearable, sau một thời gian sử dụng ứng dụng trong các bài học thực hành ở trường thì mình có một vài đóng góp nhỏ, mong rằng nó có thể giúp hoàn thiện ứng dụng hơn:
1) Về độ trễ khi click vào 1 frame trong state schema để nhập nội dung, mình nghĩ ràng chỉ cần left-click vào thôi thì sẽ khiến tốc độ sử dụng cải thiện hơn. Cũng là mình lần đầu tiên cứ click mãi không nhập vào được, nên nghĩ rằng cũng sẽ có nhiều người bị giống mình
2) Về workspace làm việc trong state schema, mình nghĩ nó khá nhỏ (mình không làm sao zoom out được?) và trong một số giải thuật dài và phức tạp thì mình không còn đủ space để nhét thêm frame vào
3) Có một lần mình lỡ đổi tên folder (folder mẹ của mẹ của folder chứa DSL4W) nhưng nó làm cho toàn bộ project bị hỏng, mình có đổi tên lại cho giống ban đầu nhưng cũng vô tác dụng
Đó là những góp ý nhỏ của mình, mong team ngày càng phát triển mạnh hơn.
Nguyễn Đình Thành Nhân - 1512261.

**Comment by esp-lab** [comment]
Chào @nhimrmh 
Cảm ở đóng góp của bạn. Nhóm sẽ xem xét và cố gắng cải thiện để giải quyết các vấn đề bạn đã đề cập. Mong sẽ nhận được phản hồi của bạn trong các phiên bản tiếp theo.

**Comment by HuuThuat1996** [comment]
Chào @nhimrmh 
Về độ trễ khi click vào 1 Stateframe để edit nội dung nhóm sẽ nghiên cứu cải thiện performance.
Về workspace nếu bạn kéo stateFrame ra hiên nó sẽ mở rộng thêm
Nếu bạn có mong muốn trở thành contributors vui lòng liên hệ nhóm bất cứ khi nào sẵn sàng.
