### ISSUE TITLE
Switching event's not defined

### ISSUE THREAD

**Issue by nxnam714** [esp-lab/DSL4Wearable#15]
Generate code for exam1: 2018/11/06 15:15:27 by ESP-LAP WAGEN Tools

There was a problem in the code generation process.
You can view the information in the log.txt file in your project directory.
*Note: Some serious errors could cause your program to malfunction.

**************************Error list*******************************

1, Event from Red to Green Not defined
2, Event from Red to Yellow Not defined
3, Event from Red to Reset Not defined
4, Event from Green to Red Not defined
5, Event from Green to Yellow Not defined
6, Event from Green to Reset Not defined
7, Event from Yellow to Green Not defined
8, Event from Yellow to Red Not defined
9, Event from Yellow to RedCount Not defined
10, Event from GreenCount to Green Not defined
11, Event from GreenCount to YellowCount Not defined
12, Event from GreenCount to Yellow Not defined
13, Event from GreenCount to Red Not defined
14, Event from RedCount to GreenCount Not defined
15, Event from RedCount to Red Not defined
16, Event from RedCount to Yellow Not defined
17, Event from RedCount to Green Not defined
18, Event from YellowCount to Green Not defined
19, Event from YellowCount to RedCount Not defined
20, Event from YellowCount to Yellow Not defined
21, Event from YellowCount to Red Not defined
22, Event from Reset to RedCount Not defined
23, Error: Not found manual code template.
![image](https://user-images.githubusercontent.com/30574102/48052165-d3a8ad80-e1d9-11e8-9784-7379b8acee46.png)
![image](https://user-images.githubusercontent.com/30574102/48052181-de634280-e1d9-11e8-8fb9-5120b86923bb.png)
![image](https://user-images.githubusercontent.com/30574102/48052189-e3c08d00-e1d9-11e8-8324-033210e92c17.png)

**Comment by esp-lab** [comment]
Hi @nxnam714 
Here are your problems: Event: you use the wrong syntax. You can read at README and make sure you download the latest version.

**Comment by esp-lab** [comment]
https://github.com/esp-lab/DSL4Wearable/issues/10
