### ISSUE TITLE
Không sử dụng được nhiều hơn 1 button

### ISSUE THREAD

**Issue by toidondoc** [esp-lab/DSL4Wearable#16]
khi sử dụng 2 button thì nó chỉ thực hiện button được thêm vào sau

**Comment by esp-lab** [comment]
Chào @toidondoc 
Cho hỏi bạn sử dụng phiên bản bao nhiêu vậy? Nếu bạn không rõ phiên bản của mình thì có thể cho biết là bạn đã pull/clone source về khoảng bao lâu rồi?

**Comment by esp-lab** [comment]
https://github.com/esp-lab/DSL4Wearable/issues/10
