### ISSUE TITLE
phiên bản từ 0.2.4 trở đi bị lỗi phần button. Cụ thể trong lab2 nó không hiểu được event "button" push. Phiên bản 0.2.1 thì vẫn ổn định.

### ISSUE THREAD

**Issue by esp-lab-1** [esp-lab/DSL4Wearable#18]

**Comment by HuuThuat1996** [comment]
Đã update bản cập nhật [beta0.2.7](https://github.com/esp-lab/DSL4Wearable/releases/tag/beta.0.2.7) sửa lỗi không nhận được biểu thức ghi nhận button được nhấn.
