### ISSUE TITLE
Cập nhật tài liệu các hàm trong stateschema

### ISSUE THREAD

**Issue by lochoang75** [esp-lab/DSL4Wearable#3]
Các bạn cho mình xin thêm thông tin cụ thể, chi tiếttiết của các hàm được sử dụng trong thư viện như cách in xuống hàng trong LCD, cách chỉnh cao độ cho buzzer.... document mình thấy khá ít không đủ để sử dụng.

**Comment by HuuThuat1996** [comment]
LCD khi bạn in  a chuỗi dài nó sẽ tự xuống dòng, Nếu bạn muốn xuống dòng căn chỉnh giữa thì bạn có thể vào code để chỉnh. Còn độ cao của buzz

**Comment by HuuThuat1996** [comment]
Bạn có thể phát ra giai diệu với cái buzz thôi chứ nếu phát ra bài hát thì mình k dám chắc

**Comment by lochoang75** [comment]
đó là lab của bọn  mình :D mình cho nó load cả cái array luôn.
