### ISSUE TITLE
Mình phát hiện bug về button. Nếu dùng nhiều button trong , dù state schema có sử dụng button gì đi chăng nữa thì code sinh ra luôn là button cuối cùng trong danh sách thiết bị.

### ISSUE THREAD

**Issue by esp-lab** [esp-lab/DSL4Wearable#5]
_Originally posted by @akkiensama in https://github.com/esp-lab/DSL4Wearable/issues/1#issuecomment-433780424_

**Comment by ngocmy177** [comment]
[issue5.zip](https://github.com/esp-lab/DSL4Wearable/files/2539323/issue5.zip)
@esp-lab mình gửi 2 file device và state của mình

**Comment by esp-lab** [comment]
Bạn có thể xem thông tin về bug này tại https://github.com/esp-lab/DSL4Wearable/issues/10
