### ISSUE TITLE
### Ví dụ sử dụng 3 đèn led để bật tắt đèn giao thông xuất dữ liệu ra màn hình LCD ###

### ISSUE THREAD

**Issue by esp-lab** [esp-lab/DSL4Wearable#6]
![capture](https://user-images.githubusercontent.com/41546531/47626316-0f4dd280-db5d-11e8-8768-212f5048a899.PNG)
### Hướng dẫn cắm mạch ### 
![capture2](https://user-images.githubusercontent.com/41546531/47626600-8fc10300-db5e-11e8-9947-a67660bca3da.PNG)

#include <LiquidCrystal_I2C.h>

int currentState = 0;
int nextState = -1;
const int red = 2;
const int green = 3;
const int yellow = 4;
LiquidCrystal_I2C lcd(0x27, 20, 4);

void stateStart();
void stateState1();
void stateState2();
void setup()
{
  pinMode(red, OUTPUT);
  pinMode(green, OUTPUT);
  pinMode(yellow, OUTPUT);
  lcd.init();
  lcd.begin(20, 4);
  lcd.backlight();
  if(currentState == 0){
    stateStart();
  }
}
void loop()
{
  switch(currentState){
    case 0:
    stateState1();
    break;
    case 1:
    stateState2();
    break;
    case 2:
    stateStart();
    break;
    default:
    break;
  }
}

void stateStart(){
  digitalWrite(red, LOW);
  digitalWrite(green, HIGH);
  digitalWrite(yellow, LOW);
  lcd.clear();
  lcd.setCursor(0,1);
  lcd.print("Xin Chao");
  delay(3000);
  currentState = 0;
}
void stateState1(){
  digitalWrite(red, LOW);
  digitalWrite(green, LOW);
  digitalWrite(yellow, HIGH);
  lcd.clear();
  lcd.setCursor(0,1);
  lcd.print("Cham");
delay(3000);
  currentState = 1;
}
void stateState2(){
  digitalWrite(red, HIGH);
  digitalWrite(green, LOW);
  digitalWrite(yellow, LOW);
  lcd.clear();
  lcd.setCursor(0,0); 
  lcd.print("Dung"); 
  delay(3000);
  currentState = 2;
}
_Chương trình khu phát sinh code ra thì thiếu lện xuất ra màn hình của LCD cái này mình cũng không biết sao nữa, trên kia là code hoàn chỉnh của nó, các bạn tham khảo nhe_

_Originally posted by @WatashiMo in https://github.com/esp-lab/DSL4Wearable/issues/1#issuecomment-433772304_

**Comment by HuuThuat1996** [comment]
Chào bạn không biết bạn clone code lâu chưa. Mình đã update fix lỗi mấy tuần trước.

**Comment by esp-lab** [comment]
Bạn có thể cập nhật bản mới nhất tại đây https://github.com/esp-lab/DSL4Wearable/releases/tag/vs0.1
