### ISSUE TITLE
Code gernerate bị lỗi khi sử dụng decision

### ISSUE THREAD

**Issue by riletan** [esp-lab/DSL4Wearable#7]
![image](https://user-images.githubusercontent.com/38369531/47707021-44414e80-dc5d-11e8-9eb8-23a138e8a40f.png)

Hi anh, em có vẽ một schema đèn giao thông như trên, nhưng code sinh ra chỉ có thế này thôi :D
Anh kiểm tra lại nhé, em cảm ơn.
/*
Source code for
/
/
Each state in the application corresponds to one the integer.
Numbered starting at 0
stateCurrent is a variable that stores the current state of the application.
onGreen: 0
/
int currentState = 0;
int nextState = -1;
/--------------------Define--------------------/
/Define LED - green output/
const int green = 2;
/Define LED - yellow output/
const int yellow = 3;
/Define LED - red output/
const int red = 4;
/Define Button output/
const int button = 5;
/--------------------END Define--------------------/
/--------------------Prototype--------------------/
void stateonGreen();
/--------------------END Prototype--------------------/
void setup()
{
pinMode(green, OUTPUT);
pinMode(yellow, OUTPUT);
pinMode(red, OUTPUT);
pinMode(button, INPUT);
if(currentState == 0){
stateonGreen();
}
}
void loop()
{
switch(currentState){
case 0:
//
break;
default:
break;
}
}
/--------------------Implement--------------------/
void stateonGreen(){
digitalWrite(green, HIGH);
digitalWrite(red, LOW);
digitalWrite(yellow, LOW);
delay(1500);
currentState = 0;
delay(200);
}
/--------------------END Implement--------------------*/

**Comment by esp-lab** [comment]
Chào bạn @riletan trong state machine không có decision. Nó đã được xóa đi. Bạn có thể download bản releases mới nhất tại đây https://github.com/esp-lab/DSL4Wearable/releases/tag/vs0.1
